In [1]:
from analytics.db import execute,query

In [2]:
query('''SELECT 
    EXTRACT(YEAR FROM order_purchase_timestamp) AS order_year,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_year
ORDER BY order_year ASC;

      ''')

   order_year  total_orders
0      2016.0           329
1      2017.0         45101
2      2018.0         54011

In [3]:
query("""SELECT * FROM customers LIMIT 5  """)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
query("""SELECT * FROM geolocation LIMIT 5  """)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545621,-46.639292,sao paulo,SP
1,01046,-23.546081,-46.644820,sao paulo,SP
2,01046,-23.546129,-46.642951,sao paulo,SP
3,01041,-23.544392,-46.639499,sao paulo,SP
4,01035,-23.541578,-46.641607,sao paulo,SP

In [5]:
query("""SELECT * FROM order_items LIMIT 5  """)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
query("""SELECT * FROM order_payments LIMIT 5  """)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [7]:
query("""SELECT * FROM order_reviews LIMIT 5  """)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,None,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,None,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [8]:
query("""SELECT * FROM orders LIMIT 5  """)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [9]:
query("""SELECT * FROM products LIMIT 5  """)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625,20,17,13

In [10]:
query("""SELECT * FROM sellers LIMIT 5  """)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [11]:
query("""SELECT * FROM category_translation LIMIT 5  """)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [12]:
query("""
    SELECT COUNT(*)                                       AS rows,
           COUNT(DISTINCT order_id)                       AS different_values,
           COUNT(*) FILTER (WHERE order_id IS NULL)       AS missing
    FROM orders
""")

    rows  different_values  missing
0  99441             99441        0

proven

In [13]:
query("""
    SELECT COUNT(*) AS rows, 
           COUNT(DISTINCT (order_id, order_item_id)) AS different_pairs 
    FROM order_items
""")

     rows  different_pairs
0  112650           112650

proven

In [14]:
query("""
    SELECT COUNT(*) AS total_rows,
           COUNT(DISTINCT (geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state)) AS distinct_rows
    FROM geolocation
""")

   total_rows  distinct_rows
0     1000163         738332

not proven

In [15]:
query("""
    SELECT COUNT(*) AS rows, 
           COUNT(DISTINCT (order_id, order_item_id,product_id , seller_id)) AS different_pairs 
    FROM order_items
""")

     rows  different_pairs
0  112650           112650

In [16]:
query("""
    SELECT COUNT(*)                                         AS rows,
           COUNT(DISTINCT customer_id)                      AS diff_customer_id,
           COUNT(DISTINCT customer_unique_id)               AS diff_unique_id,
           COUNT(*) FILTER (WHERE customer_id IS NULL)      AS missing_customer_id
    FROM customers
""")

    rows  diff_customer_id  diff_unique_id  missing_customer_id
0  99441             99441           96096                    0

not proven

In [17]:
query("""
    SELECT COUNT(*) AS rows,
           COUNT(DISTINCT order_id) AS diff_orders,
           COUNT(DISTINCT (order_id, payment_sequential)) AS diff_pairs
    FROM order_payments
""")

     rows  diff_orders  diff_pairs
0  103886        99440      103886

not proven

In [18]:
query("""
    SELECT COUNT(*) AS rows,
           COUNT(DISTINCT review_id) AS diff_reviews,
           COUNT(DISTINCT (review_id, order_id)) AS diff_pairs
    FROM order_reviews
""")

    rows  diff_reviews  diff_pairs
0  99224         98410       99224

not proven

In [19]:
query("SELECT COUNT(*) AS rows, COUNT(DISTINCT product_id) AS diff FROM products")

    rows   diff
0  32951  32951

proven

In [20]:
query("SELECT COUNT(*) AS rows, COUNT(DISTINCT seller_id) AS diff FROM sellers")

   rows  diff
0  3095  3095

proven

In [21]:
query("SELECT COUNT(*) AS rows, COUNT(DISTINCT product_category_name) AS diff FROM category_translation")

   rows  diff
0    71    71

proven

In [22]:
query("""
    SELECT COUNT(*)
    FROM orders AS o
    WHERE NOT EXISTS (
        SELECT 1 FROM customers AS c
        WHERE c.customer_id = o.customer_id
    )
""")

   count
0      0

In [23]:
query("""
    SELECT 
        MIN(order_purchase_timestamp) AS first_order,
        MAX(order_purchase_timestamp) AS last_order,
        COUNT(DISTINCT order_status) AS unique_statuses
    FROM orders
""")

          first_order          last_order  unique_statuses
0 2016-09-04 21:15:19 2018-10-17 17:30:18                8

In [24]:
query("""
    SELECT order_status, COUNT(*) AS count
    FROM orders
    GROUP BY order_status
    ORDER BY count DESC
""")

  order_status  count
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7     approved      2

In [25]:
query("""
    SELECT 
        MIN(price) AS min_price,
        ROUND(CAST(MAX(price) AS numeric), 2) AS max_price,
        ROUND(CAST(AVG(price) AS numeric), 2) AS avg_price,
        MIN(freight_value) AS min_freight,
        ROUND(CAST(MAX(freight_value) AS numeric), 2) AS max_freight
    FROM order_items
""")

   min_price  max_price  avg_price  min_freight  max_freight
0       0.85     6735.0     120.65          0.0       409.68

In [26]:
query("""
    SELECT 
        COUNT(DISTINCT product_category_name) AS unique_categories,
        COUNT(*) AS total_products
    FROM products
""")

   unique_categories  total_products
0                 73           32951